[package]
name = "air-values"
version = "0.1.0"
description = "Implementation of AIR execution info collector"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_values"
path = "src/lib.rs"

[dependencies]
air-lambda-ast = { path = "../../lambda/ast" }
air-parser = { path = "../../air-parser" }
boxed-value = { path = "../boxed-value" }
polyplets = { path = "../../polyplets" }

serde_json = "1.0"
