[package]
name = "air-lambda-ast"
description = "Definition of the AIR lambda AST"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "lambda", "ast"]
categories = ["wasm"]

[lib]
name = "air_lambda_ast"
path = "src/lib.rs"

[dependencies]
non-empty-vec = { version = "0.2.3", features = ["serde"] }

serde = { version = "1.0.144", features = ["rc", "derive"] }
serde_json = "1.0.85"
