[workspace]
members = [
    "crates/air-parser",
    "crates/polyplets",
    "crates/interpreter-interface",
    "crates/test-module",
    "crates/test-utils",
    "interpreter",
    "interpreter-lib"
]

exclude = [
    "crates/air-interpreter-wasm",
    "interpreter-lib/tests/security_tetraplets/auth_module",
    "interpreter-lib/tests/security_tetraplets/log_storage",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
