[workspace]
members = [
    "crates/test-module",
    "crates/test-utils",
    "crates/stepper-lib",
    "stepper",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
