[workspace]
members = [
    "air",
    "air-interpreter",
    "avm/server",
    "crates/air-lib/air-parser",
    "crates/air-lib/execution-info-collector",
    "crates/air-lib/interpreter-data",
    "crates/air-lib/interpreter-interface",
    "crates/air-lib/lambda/ast",
    "crates/air-lib/lambda/parser",
    "crates/air-lib/log-targets",
    "crates/air-lib/polyplets",
    "crates/air-lib/test-utils",
    "crates/air-lib/trace-handler",
    "crates/data-store",
]

exclude = [
    "air/tests/test_module/integration/security_tetraplets/auth_module",
    "air/tests/test_module/integration/security_tetraplets/log_storage",
    "crates/interpreter-wasm",
]

[profile.release]
opt-level = 3
# since the interpreter in actively development stage, these settings are true at least for a while
debug = true
overflow-checks = true
debug-assertions = false
panic = "unwind"

[patch.crates-io]
polyplets = { path = "crates/air-lib/polyplets" }

#wasmer-interface-types-fl = {version = "0.23.0", path = "../interface-types/wasmer-it"}
#it-lilo = {version = "0.4.0", path = "../interface-types/crates/it-lilo"}
#it-memory-traits = {version = "0.3.0", path = "../interface-types/crates/it-memory-traits"}
#fluence-it-types = {version = "0.3.1", path = "../interface-types/crates/it-types"}

#fluence-app-service = {version = "0.17.0", path = "../marine/fluence-app-service"}
#fluence-faas = {version = "0.16.0", path = "../marine/fluence-faas"}
#marine-runtime = {version = "0.14.0", path = "../marine/runtime"}
