[workspace]
members = [
    "air",
    "air-interpreter",
    "crates/air-parser",
    "crates/polyplets",
    "crates/interpreter-interface",
    "crates/interpreter-data",
    "crates/test-module",
    "crates/test-utils",
    "avm/server",
]

exclude = [
    "air/tests/test_module/integration/security_tetraplets/auth_module",
    "air/tests/test_module/integration/security_tetraplets/log_storage",
    "crates/air-interpreter-wasm",
]

[profile.release]
opt-level = 3
# since the interpreter in actively development stage, these settings are true at least for a while
debug = true
debug-assertions = true
overflow-checks = true
panic = "unwind"
