[package]
name = "aquamarine"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "aquamarine"
path = "src/main.rs"

[[bin]]
name = "aqua_test_module"
path = "test_module/main.rs"

[dependencies]
fluence = { git = "https://github.com/fluencelabs/rust-sdk", features = ["logger"] }
serde = { version = "1.0.116", features = ["derive"] }
serde_derive = "1.0.116"
serde_sexpr = "0.1.0"
log = "0.4.11"
serde_json = "1.0"
wasm-bindgen = "0.2.68"
