[workspace]
members = [
    "crates/air-parser",
    "crates/plets",
    "crates/test-module",
    "crates/test-utils",
    "stepper",
    "stepper-lib",
    "stepper-lib/tests/security_tetraplets/auth_module",
    "stepper-lib/tests/security_tetraplets/log_storage",
]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
