[workspace]
members = [
    "air",
    "air-interpreter",
    "avm/server",
    "crates/air-lib/air-parser",
    "crates/air-lib/execution-info-collector",
    "crates/air-lib/interpreter-data",
    "crates/air-lib/interpreter-interface",
    "crates/air-lib/lambda/ast",
    "crates/air-lib/lambda/parser",
    "crates/air-lib/log-targets",
    "crates/air-lib/polyplets",
    "crates/air-lib/test-utils",
    "crates/air-lib/trace-handler",
    "crates/data-store",
]

exclude = [
    "air/tests/test_module/integration/security_tetraplets/auth_module",
    "air/tests/test_module/integration/security_tetraplets/log_storage",
    "crates/interpreter-wasm",
]

[profile.release]
opt-level = 3
# since the interpreter in actively development stage, these settings are true at least for a while
debug = true
overflow-checks = true
debug-assertions = false
panic = "unwind"

[patch.crates-io]
polyplets = { path = "crates/air-lib/polyplets" }

it-lilo = {version = "0.4.0", git = "https://github.com/fluencelabs/interface-types", branch = "bug/allocating-more-than-2gb"}
fluence-it-types = {version = "0.3.1", git = "https://github.com/fluencelabs/interface-types", branch = "bug/allocating-more-than-2gb"}
it-memory-traits = {version = "0.3.0", git = "https://github.com/fluencelabs/interface-types", branch = "bug/allocating-more-than-2gb"}
wasmer-interface-types-fl = {version = "0.23.1", git = "https://github.com/fluencelabs/interface-types", branch = "bug/allocating-more-than-2gb"}
marine-runtime = {version = "0.14.1", git = "https://github.com/fluencelabs/marine", branch = "update-it"}
fluence-faas = {version = "0.16.1", git = "https://github.com/fluencelabs/marine", branch = "update-it"}
fluence-app-service = {version = "0.17.1", git = "https://github.com/fluencelabs/marine", branch = "update-it"}


