[package]
name = "air-interpreter-interface"
description = "Interface of the AIR interpreter"
version = "0.17.1"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/air-interpreter-interface"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/interpreter-interface"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_interface"
path = "src/lib.rs"

[dependencies]
marine-rs-sdk = {version = "0.10.2", optional = true }
fluence-it-types = { version = "0.4.1", optional = true }
air-interpreter-sede = { version = "0.1.0", path = "../interpreter-sede", features = ["msgpack"] }

marine-call-parameters = { version = "0.10.3", default-features = false }
serde = "1.0.190"
serde_json = "1.0.108"
serde_bytes = "0.11.12"

[features]
default = ["marine"]
marine = ["marine-rs-sdk", "fluence-it-types", "air-interpreter-sede/marine", "marine-call-parameters/marine-abi"]
