[package]
name = "aquavm-air-cli"
version = "0.2.9"
edition = "2021"
description = "AIR execution and printing tool"
authors = ["Fluence Labs"]
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/aquavm-air-cli"
keywords = ["fluence", "air", "tracing"]

[dependencies]
aquavm-air = { version = "0.39.0", path = "../../../air" }
air-beautifier = { version = "0.1.3", path = "../../../crates/beautifier" }
avm-data-store = { version = "0.6.1", path = "../../../crates/data-store" }
avm-interface = { version = "0.28.3", path = "../../../avm/interface" }
air-interpreter-interface = { version = "0.13.0", path = "../../../crates/air-lib/interpreter-interface", default-features = false }
air-test-utils = { version = "0.5.0",path = "../../../crates/air-lib/test-utils", optional = true }

anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive", "env"] }
itertools = "0.10.5"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.96"
tracing-subscriber = { version = "0.3.16", default-features = false, features = [ "env-filter", "json", "smallvec", "time", "fmt" ] }
atty = "0.2.14"
termcolor = "1.2.0"

[features]
default = ["wasm"]
wasm = ["air-test-utils"]

[[bin]]
name = "air"
path = "src/main.rs"
