[package]
name = "air-utils"
version = "0.3.0"
description = "AIR helper funcitions and macros"
authors = ["Fluence Labs"]
edition = "2021"
license = "AGPL-3.0-only"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_utils"
path = "src/lib.rs"
