[package]
name = "air-interpreter-signatures"
description = "AIR interpreter signatures util module"
version = "0.1.7"
authors = ["Fluence Labs"]
edition = "2021"
license = "AGPL-3.0-only"
documentation = "https://docs.rs/air-interpreter-signatures"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/interpreter-signatures"
keywords = ["fluence", "air", "programming-language"]
categories = ["wasm"]

[dependencies]
air-interpreter-cid = { version = "0.9.0", path = "../interpreter-cid" }
fluence-keypair = { version = "0.10.4", default-features = false }

bs58 = "0.5.0"
borsh = { version = "1.5.0", features = ["rc", "derive"] }
serde = { version = "1.0.190", features = ["derive"] }
thiserror = "1.0.49"
rkyv = { version = "0.7.43", features = ["validation", "strict"], optional = true }

[features]
default = ["rand"]
rand = []
