[package]
name = "air-interpreter-value"
description = "JSON value optimized for copying"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/air-interpreter-value"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/interpreter-value"
keywords = ["fluence", "air", "programming-language", "json"]
categories = ["wasm"]

[dependencies]
indexmap = "2.1.0"
serde = { version = "1.0.195", features = ["rc"] }
serde_json = "1.0.108"

[dev-dependencies]
maplit = "1.0.2"

[features]
