[package]
name = "zk-aquavm-interface"
version = "0.1.0"
description = "Interface for RISC-0 AquaVM wrapper"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
publish = true

[dependencies]
aquavm-air = { path = "../../../../../../../../air" }
serde = "1.0"
