[package]
name = "air-test-utils"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "air_test_utils"
path = "src/lib.rs"

[dependencies]
fluence = "0.6.5"
avm-server = { path = "../../avm/server", features = ["raw-avm-api"] }
serde_json = "1.0.56"
