[package]
name = "aqua-test-utils"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "aqua_test_utils"
path = "src/lib.rs"

[dependencies]
fluence = { git = "https://github.com/fluencelabs/rust-sdk", branch = "optimizations", features = ["logger"] }
aquamarine-vm = { version = "0.5.1", features = ["raw-aquamarine-vm-api"] }
serde_json = "1.0.56"
