[package]
name = "zk-aquavm"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.17.0", default-features = false, features = [ "std" ] }
zk-aquavm-interface = { path = "../../core" }
aquavm-air = { path = "../../../../../../../../../air" }

[patch.crates-io]
fluence-keypair = { git = "https://github.com/fluencelabs/trust-graph.git", branch = "lean-keypair-2" }
libp2p-identity = { git = "https://github.com/fluencelabs/rust-libp2p.git", branch = "rand-feature" }