[package]
name = "air-trace-handler"
version = "0.5.8"
description = "Implementation of AIR trace handler"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_trace_handler"
path = "src/lib.rs"

[dependencies]
air-interpreter-cid = { version = "0.7.0", path = "../interpreter-cid" }
air-interpreter-data = { version = "0.15.0", path = "../interpreter-data" }
air-log-targets = { version = "0.1.0", path = "../log-targets" }
aquavm-air-parser = { version = "0.11.0", path = "../air-parser" }
polyplets = { version = "0.5.1", path = "../polyplets" }

bimap = "0.6.3"
serde_json = "1.0.108"
log = "0.4.20"
thiserror = "1.0.50"
tracing = "0.1.40"
num-traits = "0.2.17"

[features]
default = ["rand"]
rand = ["air-interpreter-data/rand"]
