[package]
name = "air-trace-handler"
version = "0.5.12"
description = "Implementation of AIR trace handler"
authors = ["Fluence DAO", "Cloudless Labs"]
edition = "2021"
license = "AGPL-3.0-only"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_trace_handler"
path = "src/lib.rs"

[dependencies]
air-interpreter-cid = { version = "0.9.0", path = "../interpreter-cid" }
air-interpreter-data = { version = "0.17.2", path = "../interpreter-data" }
air-log-targets = { version = "0.1.0", path = "../log-targets" }
aquavm-air-parser = { version = "0.12.0", path = "../air-parser" }
polyplets = { version = "0.7.0", path = "../polyplets" }

bimap = "0.6.3"
serde_json = "1.0.108"
log = "0.4.20"
thiserror = "1.0.50"
tracing = "0.1.40"
num-traits = "0.2.17"
