[package]
name = "air-trace-handler"
version = "0.1.0"
description = "Implementation of AIR trace handler"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_trace_handler"
path = "src/lib.rs"

[dependencies]
air-interpreter-data = { path = "../interpreter-data" }
air-log-targets = { path = "../log-targets" }
air-parser = { path = "../air-parser" }

bimap = "0.6.2"
serde_json = "1.0.86"
log = "0.4.17"
thiserror = "1.0.37"
tracing = "0.1.37"
