[package]
name = "air"
version = "0.15.0"
description = "Interpreter of AIR scripts intended to coordinate request flow in the Fluence network"
authors = ["Fluence Labs"]
edition = "2018"
repository = "https://github.com/fluencelabs/aquavm"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air"
path = "src/lib.rs"
doctest = false

[dependencies]
air-parser = { path = "../crates/air-lib/air-parser" }
air-interpreter-data = { path = "../crates/air-lib/interpreter-data" }
air-interpreter-interface = { path = "../crates/air-lib/interpreter-interface" }
air-log-targets = { path = "../crates/air-lib/log-targets" }
air-trace-handler = { path = "../crates/air-lib/trace-handler" }
polyplets = { path = "../crates/air-lib/polyplets" }
marine-rs-sdk = { version = "0.6.11", features = ["logger"] }

serde = { version = "1.0.118", features = [ "derive", "rc" ] }
serde_json = "1.0.61"

jsonpath_lib-fl = "=0.3.7"

boolinator = "2.4.0"
log = "0.4.11"
thiserror = "1.0.23"
strum = "0.21"
strum_macros = "0.21"

# Keep 0.2.65 until this is resolved https://github.com/rustwasm/wasm-pack/issues/886
wasm-bindgen = "=0.2.65"

[dev_dependencies]
air-test-utils = { path = "../crates/air-lib/test-utils" }
fluence-app-service = "0.10.1"

criterion = "0.3.3"
csv = "1.1.5"
once_cell = "1.4.1"
env_logger = "0.7.1"
maplit = "1.0.2"
pretty_assertions = "0.6.1"
serde_json = "1.0.61"

[[bench]]
name = "call_benchmark"
harness = false

[[bench]]
name = "chat_benchmark"
harness = false

[[bench]]
name = "create_service_benchmark"
harness = false
