[package]
name = "boxed-value"
version = "0.1.0"
description = "Implementation of AIR execution info collector"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "boxed_value"
path = "src/lib.rs"

[dependencies]
air-lambda-ast = { path = "../../lambda/ast" }
polyplets = { path = "../../polyplets" }
thiserror = "1.0.30"

#erased-serde = "0.3.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
