[package]
name = "plets"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
name = "plets"
path = "src/lib.rs"

[dependencies]
fluence = { version = "=0.2.13", features = ["logger"] }
serde = { version = "1.0.118", features = ["rc"] }
