version: 2
jobs:
  aqua:
    docker:
      - image: circleci/rust:latest
    resource_class: medium+
    environment:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - aqua01-{{ checksum "Cargo.lock" }}
      - run: |
          rustup toolchain install nightly-2020-07-12-x86_64-unknown-linux-gnu
          rustup default nightly-2020-07-12-x86_64-unknown-linux-gnu

          rustup target add wasm32-wasi
          rustup component add rustfmt
          rustup component add clippy

          cargo install fcli

          # build a Wasm binary for interpreter
          (cd interpreter; fce build --features fce)

          # build Wasm binaries for tests
          (cd interpreter-lib/tests/; ./build_test_binaries.sh)

          cargo fmt --all -- --check --color always
          cargo check
          cargo test --release
          cargo clippy -v

      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: aqua01-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  aqua:
    jobs:
      - aqua
