version: 2
jobs:
  air:
    docker:
      - image: circleci/rust:latest
    resource_class: xlarge
    environment:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - air01-{{ checksum "Cargo.lock" }}
      - run:
          name: Install rutst toolckain and components
          command: |
            rustup toolchain install nightly-2022-03-20-x86_64-unknown-linux-gnu
            rustup default nightly-2022-03-20-x86_64-unknown-linux-gnu

            rustup target add wasm32-wasi
            rustup component add rustfmt
            rustup component add clippy
            cargo install cargo-nextest

      - run:
          name: Install marine
          command: |
            cargo install --force marine

      - run:
          name: Build wasm for interpreter
          command: |
            # build a Wasm binary for interpreter
            (cd air-interpreter; marine build --features marine)

      - run:
          name: Build Wasm for tests
          command: |
            # build Wasm binaries for tests
            (cd air/tests/test_module; ./build_test_binaries.sh)

            cargo fmt --all -- --check --color always

      - run:
          name: Run check and clippy
          command: |
            cargo check
            cargo clippy -v

      - run:
          name: Run tests
          command: |
            cicargo nextest --release

      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: air01-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  air:
    jobs:
      - air
