version: 2
jobs:
  aqua:
    docker:
      - image: circleci/rust:latest
    resource_class: medium+
    environment:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - aqua01-{{ checksum "Cargo.lock" }}
      - run: |
          rustup toolchain install nightly-2020-07-12-x86_64-unknown-linux-gnu
          rustup default nightly-2020-07-12-x86_64-unknown-linux-gnu

          rustup target add wasm32-wasi
          rustup component add rustfmt
          rustup component add clippy

          cargo install fcli
          cd stepper
          fce build --features fce

          cd ..
          cd stepper-lib/tests/security_tetraplets/auth_module
          fce build

          cd ../log_storage
          fce build

          cd ../../../../

          cargo fmt --all -- --check --color always
          cargo check -p stepper-lib
          cargo check -p stepper

          cargo test --release -p stepper-lib
          cargo test --release -p air-parser

          cargo clippy -v -p stepper-lib
          cargo clippy -v -p stepper

      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: aqua01-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  arqada:
    jobs:
      - aqua
