[package]
name = "avm-server"
description = "Fluence AIR VM"
version = "0.11.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "avm_server"
path = "src/lib.rs"

[dependencies]
fluence-faas = "0.9.0"
air-interpreter-interface = { version = "0.6.0", path = "../../crates/interpreter-interface" }
avm-data-store = { version = "0.1.0", path = "../../crates/data-store" }

anyhow = "1.0.43"
thiserror = "1.0.24"
maplit = "1.0.2"
serde_json = "1.0.61"
serde = "1.0.118"
log = "0.4.14"
parking_lot = "0.11.1"
