[package]
name = "avm-server"
description = "Fluence AIR VM"
version = "0.7.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "avm_server"
path = "src/lib.rs"

[dependencies]
fluence-faas = "0.7.0"
aqua-interpreter-interface = "0.5.0"

maplit = "1.0.2"
serde_json = "1.0.60"
serde = "=1.0.118"
log = "0.4.14"
parking_lot = "0.11.1"

[features]
# enable raw AquamarineVM API intended for testing
raw-aquamarine-vm-api = []
