[package]
name = "avm-server"
description = "Fluence AIR VM"
version = "0.25.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/avm-server"
repository = "https://github.com/fluencelabs/aquavm/tree/master/avm/server"
publish = true # this crate is used by the node
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "avm_server"
path = "src/lib.rs"

[dependencies]
air-interpreter-interface = { version = "0.11.0", path = "../../crates/air-lib/interpreter-interface" }
air-utils = { version = "0.1.0", path = "../../crates/air-lib/utils" }
avm-data-store = { version = "0.4.0", path = "../../crates/data-store" }
marine-runtime = "0.18.0"
polyplets = { version = "0.3.0", path = "../../crates/air-lib/polyplets" }
avm-interface = { version = "0.25.0", path = "../../avm/interface" }

eyre = "0.6.5"
thiserror = "1.0.29"
maplit = "1.0.2"
serde_json = "1.0.61"
serde = "1.0.118"
log = "0.4.14"
parking_lot = "0.11.1"
tracing = "0.1.35"
