[package]
name = "avm-server"
description = "Fluence AIR VM"
version = "0.11.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/avm-server"
repository = "https://github.com/fluencelabs/aquavm/avm/server"
publish = true # this crate is used by the node
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "avm_server"
path = "src/lib.rs"

[dependencies]
air-interpreter-interface = { version = "0.7.0", path = "../../crates/air-lib/interpreter-interface" }
avm-data-store = { version = "0.1.0", path = "../../crates/data-store" }
fluence-faas = "0.9.2"
polyplets = { version = "0.1.2", path = "../../crates/air-lib/polyplets" }

eyre = "0.6.5"
thiserror = "1.0.29"
maplit = "1.0.2"
serde_json = "1.0.61"
serde = "1.0.118"
log = "0.4.14"
parking_lot = "0.11.1"
