[package]
name = "air-interpreter"
version = "0.24.0"
description = "Crate-wrapper for air"
authors = ["Fluence Labs"]
edition = "2018"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_client"
crate-type = ["cdylib"]
path = "src/wasm_bindgen.rs"

[[bin]]
name = "air_interpreter_server"
path = "src/marine.rs"

[dependencies]
air = { path = "../air" }
air-log-targets = { path = "../crates/air-lib/log-targets" }

marine-rs-sdk = { version = "0.6.15", features = ["logger"] }

# Keep 0.2.65 until this is resolved https://github.com/rustwasm/wasm-pack/issues/886
wasm-bindgen = "=0.2.65"

log = "0.4.11"
serde = { version = "1.0.118", features = [ "derive", "rc" ] }
serde_json = "1.0.61"
tracing = { version = "0.1.35" }
tracing-log = { version = "0.1.3", features = [ "env_logger" ] }
tracing-subscriber = { version = "0.3.11", features = [ "env-filter" ] }

[features]
# indicates that this library should be compiled for the marine target,
# otherwise it will be compiled for the wasm bindgen target
marine = []
