[package]
name = "air-interpreter"
version = "0.9.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
name = "air_interpreter_client"
crate-type = ["cdylib"]
path = "src/wasm_bindgen.rs"

[[bin]]
name = "air_interpreter_server"
path = "src/fce.rs"

[dependencies]
air = { path = "../air" }

fluence = { version = "0.6.2", features = ["logger"] }

# Keep 0.2.65 until this is resolved https://github.com/rustwasm/wasm-pack/issues/886
wasm-bindgen = "=0.2.65"

log = "0.4.11"
serde = { version = "=1.0.118", features = [ "derive", "rc" ] }
serde_json = "1.0"

[features]
fce = ["air/fce"]
