[package]
name = "air-parser"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[build-dependencies] # <-- We added this and everything after!
lalrpop = { version = "0.19.1", features = ["lexer"] }

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"

lalrpop-util = { version = "0.19.1", features = ["lexer"] }
regex = "1.4.1"

codespan = "0.9.5"
codespan-reporting = "0.9.5"
unindent = "0.1.7"
