[package]
name = "aqua_vm"
version = "1.0.0"
authors = ["Fluence labs"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aquavm-air = { path = "../../../air" }
air-interpreter-interface = { path = "../../../crates/air-lib/interpreter-interface" }
near-sdk = "=4.0.0"
# KLUDGE: the crate has no direct dependency to getrandom; near-sdk do
getrandom = { version = "0.2.10", features = ["js"] }
uint = { version = "0.9.3", default-features = false }
serde = { version = "1.0.118", features = [ "derive", "rc" ] }
serde_json = "1.0.61"

[features]
default = []
# # available on signature checking branch
# check_signatures = ["aquavm-air/check_signatures"]
# gen_signatures = ["aquavm-air/gen_signatures"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
# nb: what is the stack size?  .cargo/config.toml sets it to 50mb for target.wasm32-wasi

# TODO
[workspace]
members = []
