[package]
name = "aqua_vm"
version = "1.0.0"
authors = ["Fluence labs"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aquavm-air = { path = "../../../air" }
air-interpreter-interface = { path = "../../../crates/air-lib/interpreter-interface" }
near-sdk = "4.1.1"
serde = { version = "1.0.118", features = [ "derive", "rc" ] }
serde_json = "1.0.61"
hashbrown = { version = "0.14.0", default-features = false }

[features]
default = []
# # available on signature checking branch
# check_signatures = ["aquavm-air/check_signatures"]
# gen_signatures = ["aquavm-air/gen_signatures"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
# nb: what is the stack size?  .cargo/config.toml sets it to 50mb for target.wasm32-wasi

# it is required to be build in own workspace, as it has special profile
[workspace]
members = []

[patch.crates-io]
fluence-keypair = { git = "https://github.com/fluencelabs/trust-graph.git", branch = "lean-keypair" }
libp2p-identity = { git = "https://github.com/fluencelabs/rust-libp2p.git", branch = "rand-feature" }
