[package]
name = "air-near-contract"
version = "0.55.0"
description = "AIR interpreter as a NEAR contract"
authors = ["Fluence labs"]
edition = "2018"
license = "Apache-2.0"
keywords = ["fluence", "air", "webassembly", "programming-language", "near"]
categories = ["wasm"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
aquavm-air = { path = "../../../air" }
air-interpreter-interface = { path = "../../../crates/air-lib/interpreter-interface" }
near-sdk = "4.1.1"
serde = { version = "1.0.190", features = [ "derive", "rc" ] }
serde_json = "1.0.108"
hashbrown = { version = "0.14.2", default-features = false }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

# it is required to be build in own workspace, as it has special profile
[workspace]
members = []

[features]
gen_signatures = ["aquavm-air/gen_signatures"]
check_signatures = ["aquavm-air/check_signatures"]

[patch.crates-io]
fluence-keypair = { git = "https://github.com/fluencelabs/trust-graph.git", branch = "lean-keypair" }
libp2p-identity = { git = "https://github.com/fluencelabs/rust-libp2p.git", branch = "rand-feature" }
