[package]
name = "avm-data-store"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "avm_data_store"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.43"
