[package]
name = "avm-data-store"
version = "0.4.1"
description = "Definition of the AVM DataStore trait"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/avm-data-store"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/data-store"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "avm_data_store"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_bytes = "0.11.9"

[dev-dependencies]
serde_json = "1.0.93"
