[package]
name = "avm-data-store"
description = "Definition of the AVM DataStore trait"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "avm_data_store"
path = "src/lib.rs"
