[package]
name = "avm-data-store"
version = "0.3.0"
description = "Definition of the AVM DataStore trait"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/avm-data-store"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/data-store"
publish = true # this crate is used by avm server that in its turn is used by the node
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "avm_data_store"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
