[package]
name = "air-interpreter-wasm"
version = "0.0.7"
authors = ["Fluence Labs"]
description = "Distribution of AIR interpreter as .wasm"
license = "Apache-2.0"
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml",
    "aquamarine.wasm"
]

[build-dependencies]

