[package]
name = "testing-framework"
version = "0.1.0"
description = "AquaVM testing framework"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/test-framework"
publish = false
keywords = ["fluence", "air", "test"]

[lib]
name = "air_test_framework"
path = "src/lib.rs"

[dependencies]
serde_json = "1.0.61"
nom = "7.1.1"
