[package]
name = "wasm-air-beautify"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
description = "WASM module for air-beautify"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "beautifier"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# 0.2.79: a function can return Result<..., JsError>.
wasm-bindgen = { version = "=0.2.80", features = ["serde-serialize"] }
air-beautifier = { path = "../../../crates/beautifier" }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
