[package]
name = "zk-aquavm"
version = "0.1.0"
description = "RISC-0 guest wrapper for AquaVM"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
risc0-zkvm = { version = "0.19.1", default-features = false, features = [ "std" ] }
zk-aquavm-interface = { path = "../../core" }
aquavm-air = { path = "../../../../air", version = "0.55.0" }

[patch.crates-io]
fluence-keypair = { git = "https://github.com/fluencelabs/trust-graph.git", branch = "lean-keypair-2" }
libp2p-identity = { git = "https://github.com/fluencelabs/rust-libp2p.git", branch = "rand-feature" }
