[package]
name = "beautifier"
version = "0.1.0"
description = "AIR human-readable format transformer library"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/beautifier"
publish = false
keywords = ["fluence", "air", "programming-language"]

[lib]
name = "air_beautifier"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
air-parser = { path = "../air-lib/air-parser" }
thiserror = "1.0.30"
