[http]
timeout = 30                # timeout for each HTTP request, in seconds
multiplexing = false        # HTTP/2 multiplexing

[net]
retry = 50                  # network retries

[target.wasm32-wasi]
rustflags = [
    "-C", "link-args=-zstack-size=52428800",
]

[registries]
# fluence = { index = "git://crates.fluence.dev/index", token = "yMHU2kPlaic5A9KfzU8v0dPuHJ5qjbgv" }
fluence = { index = "git://crates.fluence.dev/index" }
