[net]
retry = 50                  # network retries

[target.wasm32-wasi]
rustflags = [
    "-C", "link-args=-zstack-size=52428800",
]

[build]
profiler = true

[registries]
fluence = { index = "git://crates.fluence.dev/index" }
