[package]
name = "polyplets"
version = "0.1.2"
description = "Security primitives to verify origin of service calls in Fluence network"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/polyplets"
repository = "https://github.com/fluencelabs/crates/polyplets"
publish = true # this crate is used by the avm server that in its turn is used by the node
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["authentication"]

[lib]
name = "polyplets"
path = "src/lib.rs"

[dependencies]
marine-rs-sdk = { version = "0.6.11", features = ["logger"] }
serde = { version = "1.0.118", features = ["rc", "derive"] }

