[package]
name = "polyplets"
version = "0.5.1"
description = "Security primitives to verify origin of service calls in Fluence network"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/polyplets"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/polyplets"
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["authentication"]

[lib]
name = "polyplets"
path = "src/lib.rs"

[dependencies]
marine-call-parameters = { version = "0.10.2", default-features = false }

serde = { version = "1.0.190", features = ["rc", "derive"] }
