[package]
name = "air-interpreter-sede"
description = "AIR interpreter serialization and deserialization util module"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/air-interpreter-sede"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/interpreter-sede"
keywords = ["fluence", "air", "programming-language", "TODO"]
categories = ["wasm"]

[dependencies]
