[package]
name = "air-interpreter-sede"
description = "AIR interpreter serialization and deserialization util module"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/air-interpreter-sede"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/interpreter-sede"
keywords = ["fluence", "air", "programming-language", "TODO"]
categories = ["wasm"]

[dependencies]
rmp-serde = { version = "1.1.2", optional = true }
serde = { version = "1.0.190" }
serde_json = { version = "1.0.108" }
marine-rs-sdk = { version = "0.14.0", optional = true }
unsigned-varint = { version = "0.8.0", default-features = false, features = ["std"] }
thiserror = "1.0.50"
serde_bytes = "0.11.12"

[features]
default = []
serde_json = []
rmp-serde = ["dep:rmp-serde"]
marine = ["dep:marine-rs-sdk"]
json = ["serde_json"]
msgpack = ["rmp-serde"]
