[package]
name = "interpreter-interface"
description = "Interface of the Aquamarine interpreter"
version = "0.2.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "interpreter_interface"
path = "src/lib.rs"

[dependencies]
fluence = "0.2.18"
fluence-it-types = "0.1.0"

serde = "=1.0.118"
