[package]
name = "air-interpreter-cid"
description = "AIR interpreter CID util module"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language", "cid", "ipld"]
categories = ["wasm"]

[lib]
name = "air_interpreter_cid"
path = "src/lib.rs"

[dependencies]
cid = { version = "0.9.0", default-features = false, features = ["std"] }
multihash = { version = "0.17.0", default-features = false, features = ["multihash-impl", "std", "sha2"] }
serde = "1.0.147"
serde_json = "1.0.89"
