# https://nexte.st/book/configuration.html
[store]
dir = "target/nextest"

[profile.default]
retries = 0
test-threads = "num-cpus"
threads-required = 1
status-level = "pass"
final-status-level = "fail"
failure-output = "immediate"
success-output = "never"
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 2 }
leak-timeout = "100ms"

[profile.ci]
[profile.ci.junit]
path = "junit.xml"
