[package]
name = "air-log-targets"
version = "0.1.0"
description = "Definition of global consts used for logging"
authors = ["Fluence Labs"]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-log-targets"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_log_targets"
path = "src/lib.rs"
