[package]
name = "air-beautify-wasm"
version = "0.3.9"
authors = ["Fluence DAO", "Cloudless Labs"]
edition = "2021"
description = "WASM module for air-beautify"
license = "AGPL-3.0-only"
publish = false
keywords = ["fluence", "air", "beautifier"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# 0.2.79: a function can return Result<..., JsError>.
wasm-bindgen = { version = "=0.2.83", features = ["serde-serialize"] }
air-beautifier = { version = "0.4.3", path = "../../../crates/beautifier" }
