[package]
name = "air-interpreter-starlark"
description = "Interfacing for executing Starlark scripts from AquaVM"
authors = ["Fluence DAO", "Cloudless Labs"]
license = "AGPL-3.0-only"
version = "0.1.0"
edition = "2021"
documentation = "https://docs.rs/air-interpreter-starlark"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/interpreter-starlark"
keywords = ["fluence", "air", "programming-language"]
categories = ["wasm"]

[dependencies]
allocative = "0.3.3"
anyhow = "1.0.86"
polyplets = { version = "0.7.0", path = "../polyplets" }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.120"
starlark = "0.12.0"

air-interpreter-value = { version = "0.1.0", path = "../interpreter-value", features = ["starlark"] }
