[package]
name = "cidify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
air-interpreter-cid = { version = "0.2.0", path = "../../crates/air-lib/interpreter-cid" }
air-interpreter-data = { version = "0.6.0", path = "../../crates/air-lib/interpreter-data" }
serde = { version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
