[package]
name = "stepper-interface"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"

[lib]
name = "stepper_interface"
path = "src/lib.rs"

[dependencies]
fluence = { git = "https://github.com/fluencelabs/rust-sdk" }
serde = "1.0.118"
