[package]
name = "air-test-utils"
version = "0.2.1"
description = "Test utils for the AIR interpreter"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm/crates/air-lib/test-utils"
publish = false
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["wasm"]

[lib]
name = "air_test_utils"
path = "src/lib.rs"

[dependencies]
air = { path = "../../../air" }
air-interpreter-interface = { path = "../interpreter-interface" }
avm-server = { path = "../../../avm/server" }
marine-rs-sdk = "0.6.13"

serde_json = "1.0.61"
