[package]
name = "air-test-utils"
version = "0.18.0"
description = "Test utils for the AIR interpreter"
authors = ["Fluence DAO", "Cloudless Labs"]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-test-utils"
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["wasm"]

[lib]
name = "air_test_utils"
path = "src/lib.rs"

[dependencies]
aquavm-air = { version = "0.63.0", path = "../../../air" }
air-interpreter-cid = { version = "0.9.0", path = "../interpreter-cid" }
air-interpreter-data = { version = "0.17.2", path = "../interpreter-data" }
air-interpreter-interface = { version = "0.19.0", path = "../interpreter-interface" }
air-interpreter-sede = { version = "0.1.0", path = "../interpreter-sede" }
air-interpreter-signatures = { version = "0.1.7", path = "../interpreter-signatures" }
avm-interface = { version = "0.32.1", path = "../../../avm/interface" }
avm-server = { version = "0.38.0", path = "../../../avm/server" }
marine-rs-sdk = "0.14.0"

object-pool = "0.5.4"
once_cell = "1.17.1"
semver = "1.0.17"
serde_json = "1.0.108"
serde = { version = "1.0.190", features = ["derive"] }
fluence-keypair = "0.10.4"
ed25519-dalek = "2.1.0"
rand_chacha = "0.3.1"
sha2 = "0.10.6"
air-interpreter-value = { version = "0.1.0", path = "../interpreter-value" }
marine-wasm-backend-traits = "0.7.0"
marine-wasmtime-backend = "0.7.0"
futures = "0.3.30"

tokio = {version = "1.28.2", features = ["rt", "macros"]}

[dev-dependencies]
maplit = "1.0.2"

[features]
test_with_native_code = []
