[package]
name = "air-test-utils"
version = "0.4.0"
description = "Test utils for the AIR interpreter"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["wasm"]

[lib]
name = "air_test_utils"
path = "src/lib.rs"

[dependencies]
air = { path = "../../../air" }
air-interpreter-cid = { version = "0.1.0", path = "../interpreter-cid" }
air-interpreter-data = { path = "../interpreter-data" }
air-interpreter-interface = { path = "../interpreter-interface" }
avm-interface = { path = "../../../avm/interface" }
avm-server = { path = "../../../avm/server" }
marine-rs-sdk = "0.7.1"

fstrings = "0.2.3"
object-pool = "0.5.4"
once_cell = "1.16.0"
semver = "1.0.16"
serde_json = "1.0.91"
serde = { version = "1.0.151", features = ["derive"] }

[dev-dependencies]
maplit = "1.0.2"

[features]
test_with_native_code = []
