[package]
name = "air-lambda-parser"
description = "Parser of an AIR lambda"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "parser", "lalrpop"]
categories = ["wasm"]

[lib]
name = "air_lambda_parser"
path = "src/lib.rs"

[build-dependencies]
lalrpop = "0.19.8"

[dependencies]
air-lambda-ast = { path = "../ast" }

lalrpop-util = "0.19.8"
regex = "1.6.0"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
multimap = "0.8.3"

# TODO: hide serde behind a feature
serde = { version = "1.0.144", features = ["rc", "derive"] }
serde_json = "1.0.85"

itertools = "0.10.4"
thiserror = "1.0.34"
