name: "air"

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  air:
    name: "air"
    runs-on: builder

    environment:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nighlty-2022-06-30
          target: wasm32-wasi
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - run: |
          cargo install --force marine

          # build a Wasm binary for interpreter
          (cd air-interpreter; marine build --features marine)

          # build Wasm binaries for tests
          (cd air/tests/test_module; ./build_test_binaries.sh)

          cargo fmt --all -- --check --color always
          cargo check
          cargo test --release
          # The memory sanitizer on cargo test has false positive even on empty project.
          for san in address leak; do
              RUSTFLAGS="-Z sanitizer=$san" cargo test --features test_with_native_code --target x86_64-unknown-linux-gnu
          done
          cargo clippy -v
