name: "aquavm"

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  RUST_TEST_THREADS: 1
  CARGO_HOME: "/usr/local/cargo"

jobs:
  aquavm:
    name: "Run tests"
    runs-on: builder

    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo install marine

      - name: Build Wasm binary for interpreter
        run: marine build --features marine
        working-directory: air-interpreter

      - name: Build Wasm binary for tests
        run: ./build_test_binaries.sh
        working-directory: air/tests/test_module

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo check
        run: cargo check

      - name: Run cargo test
        run: |
          cargo test --release
          # Check that it does compile
          cargo bench --no-run
          # The `memory` sanitizer on cargo test has false positive even on empty project.
          for san in address leak; do
              RUSTFLAGS="-Z sanitizer=$san" cargo test --features test_with_native_code --target x86_64-unknown-linux-gnu
          done

      - name: Run cargo clippy
        run: cargo clippy -v
