name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "!**.md"
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: true
  CARGO_HOME: "${{ github.workspace }}/cargo"

jobs:
  rust-peer:
    name: "Build rust-peer snapshot"
    runs-on: builder

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout rust-peer
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/rust-peer

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: external

      - name: Use local dependencies
        run: |
          sed -i 's#\(avm-server =\) .*#\1 { git = "https://github.com/fluencelabs/aquavm", branch = "${{ github.head_ref }}" }#g' Cargo.toml

      - name: Run cargo build
        run: cargo build --release -p particle-node

      - name: Install cargo-nextest
        run: cargo install --locked cargo-nextest@0.9.22

      - name: Run cargo nextest
        run: cargo nextest run --release --all-features --no-fail-fast --retries 10 --test-threads 10

      - name: Import secrets
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          secrets: |
            kv/docker-registry/basicauth/ci username | DOCKER_USERNAME ;
            kv/docker-registry/basicauth/ci password | DOCKER_PASSWORD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.fluence.dev
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push snapshot
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: .github/snapshot/Dockerfile
          tags: |
            docker.fluence.dev/aquavm:${{ github.head_ref }}
          labels: |
            sha=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
