name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  aquavm:
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  rust-peer:
    needs:
      - aquavm

    uses: fluencelabs/rust-peer/.github/workflows/snapshot.yml@update-e2e
    with:
      image-name: "docker.fluence.dev/aquavm"
      cargo-dependencies: |
        [
          {
            "package": "avm-server",
            "version": "=${{ needs.aquavm.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "air-interpreter-wasm",
            "version": "=${{ needs.aquavm.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]

  fluence-js-tests:
    name: "fluence-js"
    needs:
      - aquavm
      - rust-peer

    uses: fluencelabs/fluence-js/.github/workflows/tests.yml@master
    with:
      avm-version: "${{ needs.aquavm.outputs.avm-version }}"
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"

  fluence-js:
    needs:
      - aquavm

    uses: fluencelabs/fluence-js/.github/workflows/snapshot.yml@master
    with:
      avm-version: "${{ needs.aquavm.outputs.avm-version }}"

  aqua:
    needs:
      - fluence-js

    uses: fluencelabs/aqua/.github/workflows/snapshot.yml@main
    with:
      fluence-js-version: "${{ needs.fluence-js.outputs.fluence-js-version }}"

  aqua-playground:
    needs:
      - fluence-js
      - aqua
      - rust-peer

    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      fluence-js-version: "${{ needs.fluence-js.outputs.fluence-js-version }}"
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"

  registry:
    needs:
      - aqua-snapshot
      - rust-peer

    uses: fluencelabs/registry/.github/workflows/tests.yml@main
    with:
      aqua-version: "${{ needs.aqua.outputs.aqua-version }}"
      rust-peer-image: "${{ needs.rust-peer.outputs.rust-peer-image }}"
