name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "!**.md"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  snapshot:
    name: "aquavm"
    uses: ./.github/workflows/snapshot.yml

  rust-peer:
    name: "rust-peer"
    needs:
      - snapshot

    uses: fluencelabs/rust-peer/.github/workflows/snapshot.yml@rust-peer-snapshot-workflow
    with:
      image-name: "docker.fluence.dev/aquavm"
      avm-server-version: '{ git = "https://github.com/fluencelabs/aquavm", branch = "${{ github.head_ref }}" }'
      air-interpreter-wasm-version: '{ version = "${{ needs.snapshot.outputs.avm-interpreter-wasm-version }}, registry "fluence" }'

  fluence-js-tests:
    name: "fluence-js"
    needs:
      - snapshot

    uses: fluencelabs/fluence-js/.github/workflows/tests.yml@master
    with:
      avm-version: ${{ needs.snapshot.outputs.avm-version }}

  fluence-js-snapshot:
    name: "fluence-js"
    needs:
      - snapshot

    uses: fluencelabs/fluence-js/.github/workflows/snapshot.yml@master
    with:
      avm-version: ${{ needs.snapshot.outputs.avm-version }}

  aqua-snapshot:
    name: "aqua"
    needs:
      - fluence-js-snapshot

    uses: fluencelabs/aqua/.github/workflows/snapshot.yml@main
    with:
      fluence-js-version: ${{ needs.fluence-js-snapshot.outputs.fluence-js-version }}

  aqua-playground:
    needs:
      - fluence-js-snapshot
      - aqua-snapshot
      - rust-peer

    uses: fluencelabs/aqua-playground/.github/workflows/tests.yml@master
    with:
      fluence-js-version: ${{ needs.fluence-js-snapshot.outputs.fluence-js-version }}
      aqua-version: ${{ needs.aqua-snapshot.outputs.aqua-version }}
      rust-peer-image: ${{ needs.rust-peer.outputs.rust-peer-image }}
