# run locally like this:
# act -b -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 -j publish-interpreter -s "NPM_TOKEN=uuid-uuid-uuid-uuid"

name: "publish-interpreter"

on:
  push:
    branches:
      - "master"

jobs:
  npm-publish:
    name: "Publish Aquamarine to NPM"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

### Prepare cargo & toolchains
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust toolchain with wasm32-unknown-unknown
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Install wasm32-wasi
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-wasi
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: update
          args: --aggressive

### Calculate FINAL_VERSION
      - name: Install jq & sponge
        run: sudo apt-get update && sudo apt-get --yes --force-yes install jq moreutils

      - name: Install cargo-show
        run: cargo install cargo-show || true

      - name: Get versions from npm & crates.io, and take the highest one
        run: |
          yarn global add semver
          PATH="$(yarn global bin):$PATH"
          JS_VERSION="$(yarn info --silent @fluencelabs/aquamarine-stepper version || true)"
          RS_VERSION="$((cargo show --json air-interpreter-wasm | jq -r .crate.max_version) 2>/dev/null || true)"
          MAX_VERSION="$(semver "$JS_VERSION" "$RS_VERSION" "0.0.0" | tail -n1)"
          FINAL_VERSION"$(semver --increment patch "$MAX_VERSION")"
          echo "FINAL_VERSION=$FINAL_VERSION" | tee -a $GITHUB_ENV

### === JavaScript package release ===
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        continue-on-error: true

      - name: Build aquamarine.wasm for JS clients
        run: wasm-pack build $GITHUB_WORKSPACE/stepper --no-typescript --release -d $(pwd)/pkg

      - name: Generate aquamarine.wasm.base64.js
        run: |
          cat << EOF > pkg/aquamarine.wasm.base64.js
          export const wasmBs64 = "$(base64 -w0 pkg/aquamarine_client_bg.wasm)";
          EOF

    ### Generate index files so import works as: | import {wasmBs64} from "@fluencelabs/aquamarine-stepper"; |
      - name: Generate index.js & index.d.ts
        run: |
          cat << EOF > index.js
          export * from "./aquamarine.wasm.base64.js";
          EOF

          cp index.js index.d.ts
        working-directory: pkg

      - name: Generate aquamarine.wasm.base64.d.ts
        run: |
          cat << EOF > aquamarine.wasm.base64.d.ts
          export const wasmBs64: string;
          EOF
        working-directory: pkg

      - name: Prepare package.json for publishing
        run: |
          cat pkg/package.json | jq --arg name aquamarine.wasm.base64.js \
            '. + {
              files: [ "aquamarine.wasm.base64.js", "aquamarine.wasm.base64.d.ts",  "index.js", "index.d.ts" ],
              "name": "@fluencelabs/aquamarine-stepper",
              "description": "Aquamarine IR interpreter as base64 WASM",
              "main": "index.js",
              "repository": "https://github.com/fluencelabs/aquamarine",
              "author": "Fluence Labs",
              "license": "Apache 2.0",
              "private": false,
              "main": "index.js",
              "types": "index.d.ts"
            }' > pkg/package_new.json

             cat pkg/package_new.json
             mv pkg/package_new.json pkg/package.json

    ### Set version
      - name: Set version to ${{ env.FINAL_VERSION }}
        run: yarn version --new-version ${{ env.FINAL_VERSION }} --no-git-tag-version
        working-directory: pkg

    ### Add README so it appears on npmjs.org
      - run: |
          cat <<EOF > README.md
          # Aquamarine IR interpreter as base64 WASM
          EOF
        working-directory: pkg

    ### Publish aquamarine-stepper to NPM
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: pkg/package.json
          access: public
          check-version: false
          token: ${{ secrets.NPM_TOKEN }}

### === Rust package release ===
      - name: Install fcli toml-cli
        run: cargo install fcli toml-cli || true

      - name: Build aquamarine.wasm for node
        run: fce build --release -p aquamarine --features fce
        working-directory: stepper

      - name: Copy aquamarine.wasm to air-interpreter-wasm
        run: cp target/wasm32-wasi/release/aquamarine.wasm crates/air-interpreter-wasm/aquamarine.wasm

      - name: Set project version to ${{ env.FINAL_VERSION }}
        run: |
          PATH="~/.cargo/bin:$PATH"
          toml set Cargo.toml package.version "${{ env.FINAL_VERSION }}" | sponge Cargo.toml
        working-directory: crates/air-interpreter-wasm

      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --allow-dirty
        working-directory: crates/air-interpreter-wasm

### Create a pre-release
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.FINAL_VERSION }}"
          prerelease: true
          title: "Aquamarine ${{ env.FINAL_VERSION }}"
          files: |
            LICENSE
            target/wasm32-wasi/release/aquamarine.wasm
