# Compatibility workflow to call from not updated E2E from other repos
name: Publish snapshots

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "master"
      cargo-dependencies:
        description: "Cargo dependencies map"
        type: string
    outputs:
      cargo-version:
        description: "Cargo snapshot version"
        value: ${{ jobs.cargo-snapshot.outputs.version }}
      avm-version:
        description: "@fluencelabs/avm version"
        value: ${{ jobs.publish-avm.outputs.version }}
      air-beautify-wasm-version:
        description: "air-beautify-wasm version"
        value: ${{ jobs.publish-beautify.outputs.version }}

jobs:
  wasm:
    uses: ./.github/workflows/snapshots/air-interpreter-wasm.yml
    with:
      ref: ${{ inputs.ref }}

  cargo-snapshot:
    needs: wasm
    uses: ./.github/workflows/snapshots/cargo.yml
    with:
      ref: ${{ inputs.ref }}

  publish-avm:
    needs: wasm
    uses: ./.github/workflows/snapshots/avm.yml
    with:
      ref: ${{ inputs.ref }}

  publish-air-beautify:
    uses: ./.github/workflows/snapshots/air-beautify-wasm.yml
    with:
      ref: ${{ inputs.ref }}
