name: Publish air-beautify-wasm snapshot

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "master"
    outputs:
      version:
        description: "@fluencelabs/air-beautify-wasm version"
        value: ${{ jobs.snapshot.outputs.version }}

env:
  FORCE_COLOR: true

jobs:
  snapshot:
    name: "Publish air-beautify-wasm snapshot"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    outputs:
      version: "${{ steps.snapshot.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout aquavm
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/aquavm
          ref: ${{ inputs.ref }}

      - name: Import secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/npm-registry/basicauth/ci token | NODE_AUTH_TOKEN

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"

      - name: Build air-beautify-wasm
        run: |
          rm -rf pack
          wasm-pack build --release
        working-directory: tools/wasm/air-beautify-wasm

      - name: Generate snapshot version
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Publish snapshot
        id: snapshot
        uses: fluencelabs/github-actions/npm-publish-snapshot@main
        with:
          working-directory: tools/wasm/air-beautify-wasm/pkg
          id: ${{ steps.version.outputs.id }}
