[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.4.1"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
air-utils = { path = "../utils" }
air-parser = { path = "../air-parser" }
# TODO version?
air-interpreter-interface = { path = "../interpreter-interface" }
air-interpreter-cid = { path = "../interpreter-cid" }

serde = {version = "1.0.147", features = ["derive", "rc"]}
serde_json = "1.0.89"
semver = { version = "1.0.14", features = ["serde"] }
once_cell = "1.16.0"
tracing = "0.1.37"
