[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.17.2"
authors = ["Fluence Labs"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-interpreter-data"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
air-utils = { version = "0.3.0", path = "../utils" }
aquavm-air-parser = { version = "0.12.0", path = "../air-parser" }
air-interpreter-cid = { version = "0.9.0", path = "../interpreter-cid", features = ["rkyv"] }
air-interpreter-signatures = { version = "0.1.7", path = "../interpreter-signatures", features = ["rkyv"] }
air-interpreter-sede = { version = "0.1.0", path = "../interpreter-sede", features = ["msgpack"] }
air-interpreter-value = { version = "0.1.0", path = "../interpreter-value" }
polyplets = { version = "0.7.0", path = "../polyplets", features = ["rkyv"] }

fluence-keypair = { version = "0.10.4", default-features = false }
serde = {version = "1.0.190", features = ["derive", "rc"]}
serde_json = { version = "1.0.95", features = ["raw_value"] }
semver = { version = "1.0.17", features = ["serde"] }
once_cell = "1.17.1"
tracing = "0.1.40"
newtype_derive = "0.1.6"
num-traits = "0.2.17"
thiserror = "1.0.50"
serde_bytes = "0.11.13"
rkyv = { version = "0.7.43", features = ["validation", "strict"] }
rmp-serde = "1.1.2"
