[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.6.2"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
air-utils = { version = "0.1.0", path = "../utils" }
air-parser = { version = "0.7.2", path = "../air-parser" }
air-interpreter-interface = { version = "0.12.1", path = "../interpreter-interface" }
air-interpreter-cid = { version = "0.2.0", path = "../interpreter-cid" }
polyplets = { version = "0.3.2", path = "../polyplets" }

serde = {version = "1.0.152", features = ["derive", "rc"]}
serde_json = "1.0.92"
semver = { version = "1.0.16", features = ["serde"] }
once_cell = "1.17.0"
tracing = "0.1.37"
