[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.2.2"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
serde = {version = "1.0.118", features = ["derive", "rc"]}
serde_json = "1.0.61"
semver = { version = "1.0.3", features = ["serde"] }
once_cell = "1.8.0"
tracing = "0.1.35"
