[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.11.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-interpreter-data"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
air-utils = { path = "../utils" }
aquavm-air-parser = { path = "../air-parser" }
air-interpreter-cid = { path = "../interpreter-cid" }
air-interpreter-signatures = { path = "../interpreter-signatures" }
polyplets = { version = "0.5.0", path = "../polyplets" }

serde = {version = "1.0.164", features = ["derive", "rc"]}
serde_json = { version = "1.0.95", features = ["raw_value"] }
semver = { version = "1.0.17", features = ["serde"] }
once_cell = "1.17.1"
tracing = "0.1.37"
newtype_derive = "0.1.6"
num-traits = "0.2.15"
rkyv = { version = "0.7.42", features = ["validation", "std"], optional = true, default-features = false }
thiserror = { version = "1.0.48", optional = true }
borsh = { version = "0.10.3", features = ["rc"], optional = true }

[features]
rkyv = [ "dep:rkyv", "dep:thiserror", "air-interpreter-cid/rkyv", "air-interpreter-signatures/rkyv" ]
borsh = [ "dep:borsh", "air-interpreter-cid/borsh" ]
# KLUDGE
default = ["borsh"]
