[package]
name = "air-trace"
version = "0.2.4"
edition = "2021"
description = "AIR performance tracing tool"
authors = ["Fluence Labs"]
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "tracing"]

[dependencies]
air = { version = "0.36.0", path = "../../../air" }
air-test-utils = { version = "0.4.2",path = "../../../crates/air-lib/test-utils", optional = true }
air-interpreter-interface = { version = "0.12.1", path = "../../../crates/air-lib/interpreter-interface", default-features = false }
avm-data-store = { version = "0.4.1", path = "../../../crates/data-store" }
avm-interface = { version = "0.28.1", path = "../../../avm/interface" }

anyhow = "1.0.69"
clap = { version = "4.1.4", features = ["derive", "env"] }
itertools = "0.10.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
tracing-subscriber = { version = "0.3.16", default-features = false, features = [ "env-filter", "json", "smallvec", "time", "fmt" ] }

[features]
default = ["wasm"]
wasm = ["air-test-utils"]
