[package]
name = "air-trace"
version = "0.2.1"
edition = "2021"
description = "AIR performance tracing tool"
authors = ["Fluence Labs"]
license = "Apache-2.0"
publish = false
keywords = ["fluence", "air", "tracing"]

[dependencies]
air = { path = "../../../air" }
air-test-utils = { path = "../../../crates/air-lib/test-utils", optional = true }
air-interpreter-interface = { path = "../../../crates/air-lib/interpreter-interface", default-features = false }
avm-data-store = { path = "../../../crates/data-store" }
avm-interface = { path = "../../../avm/interface" }

anyhow = "1.0.64"
clap = { version = "3.2.20", features = ["derive", "env"] }
itertools = "0.10.3"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
tracing-subscriber = { version = "0.3.15", default-features = false, features = [ "env-filter", "json", "smallvec", "time", "fmt" ] }

[features]
default = ["wasm"]
wasm = ["air-test-utils"]
